spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.3.3:5432/payment
    username: nttdata
    password: nttdata
  #schema:
  #  - classpath:sql/department.sql
  # - classpath:sql/employee.sql

  thymeleaf:
    cache: false
    mode: HTML
    #  cache: false
    encoding: UTF-8

  devtools:
    restart:
      enabled: true
      exclude: "static/**"
